// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ERC4626} from "@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {IERC20, IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";
import {AggregatorV3Interface} from "@chainlink/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol";

/// @title UsdSavingsVault
/// @notice ERC-4626 savings vault whose holdings are valued in USD through a Chainlink price feed.
///         A RISK_MANAGER caps total deposits in USD terms and sets an entry fee (bps) paid to a fee recipient.
/// @dev Glue code generated by Blockchain Lab Forge. Components: OpenZeppelin ERC4626 + AccessControl (v5.7.0),
///      Chainlink AggregatorV3Interface (chainlink-evm). Deposits stop automatically if the oracle is stale or invalid.
contract UsdSavingsVault is ERC4626, AccessControl {
    using Math for uint256;
    using SafeERC20 for IERC20;

    bytes32 public constant RISK_MANAGER_ROLE = keccak256("RISK_MANAGER_ROLE");
    uint256 public constant MAX_FEE_BPS = 500; // 5%
    uint256 private constant BPS = 10_000;

    AggregatorV3Interface public immutable priceFeed;
    uint8 private immutable _feedDecimals;
    uint8 private immutable _assetDecimals;

    /// @notice Maximum total value of vault assets in USD (18 decimals). 0 = no cap.
    uint256 public depositCapUsd;
    /// @notice Entry fee in basis points, taken from each deposit/mint.
    uint256 public entryFeeBps;
    /// @notice Receiver of entry fees.
    address public feeRecipient;
    /// @notice Maximum accepted age of the oracle answer, in seconds.
    uint256 public maxPriceAge;

    event DepositCapUpdated(uint256 capUsd);
    event EntryFeeUpdated(uint256 feeBps, address recipient);
    event MaxPriceAgeUpdated(uint256 maxAge);

    error InvalidPrice(int256 answer);
    error StalePrice(uint256 updatedAt, uint256 maxAge);
    error FeeTooHigh(uint256 feeBps);
    error ZeroAddress();

    constructor(
        IERC20Metadata asset_,
        AggregatorV3Interface feed_,
        string memory name_,
        string memory symbol_,
        address admin,
        uint256 capUsd,
        uint256 maxAge
    ) ERC20(name_, symbol_) ERC4626(asset_) {
        if (admin == address(0) || address(feed_) == address(0)) revert ZeroAddress();
        priceFeed = feed_;
        _feedDecimals = feed_.decimals();
        _assetDecimals = asset_.decimals();
        depositCapUsd = capUsd;
        maxPriceAge = maxAge;
        feeRecipient = admin;
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(RISK_MANAGER_ROLE, admin);
    }

    // ---------------------------------------------------------------- oracle

    /// @notice Price of one whole asset unit in USD, 18 decimals. Reverts if the feed is stale or non-positive.
    function assetPriceUsd() public view returns (uint256) {
        (,int256 answer,, uint256 updatedAt,) = priceFeed.latestRoundData();
        if (answer <= 0) revert InvalidPrice(answer);
        if (block.timestamp - updatedAt > maxPriceAge) revert StalePrice(updatedAt, maxPriceAge);
        // forge-lint: disable-next-line(unsafe-typecast)
        return uint256(answer) * 10 ** (18 - _feedDecimals); // answer > 0 checked above
    }

    function _tryPrice() internal view returns (bool ok, uint256 price) {
        try priceFeed.latestRoundData() returns (uint80, int256 answer, uint256, uint256 updatedAt, uint80) {
            if (answer <= 0 || updatedAt > block.timestamp || block.timestamp - updatedAt > maxPriceAge) return (false, 0);
            // forge-lint: disable-next-line(unsafe-typecast)
            return (true, uint256(answer) * 10 ** (18 - _feedDecimals));
        } catch {
            return (false, 0);
        }
    }

    /// @notice USD value (18 decimals) of an amount of the underlying asset.
    function assetsToUsd(uint256 assets) public view returns (uint256) {
        return assets.mulDiv(assetPriceUsd(), 10 ** _assetDecimals);
    }

    /// @notice USD value (18 decimals) of everything the vault holds.
    function totalAssetsUsd() external view returns (uint256) {
        return assetsToUsd(totalAssets());
    }

    /// @notice USD value (18 decimals) of a holder's position.
    function balanceOfUsd(address account) external view returns (uint256) {
        return assetsToUsd(convertToAssets(balanceOf(account)));
    }

    // ---------------------------------------------------------------- limits

    /// @dev ERC-4626: must not revert. Returns 0 when the oracle is unusable.
    function maxDeposit(address) public view override returns (uint256) {
        if (depositCapUsd == 0) return type(uint256).max;
        (bool ok, uint256 price) = _tryPrice();
        if (!ok) return 0;
        uint256 held = totalAssets().mulDiv(price, 10 ** _assetDecimals);
        if (held >= depositCapUsd) return 0;
        // gross deposit (incl. fee) the remaining USD headroom allows
        return (depositCapUsd - held).mulDiv(10 ** _assetDecimals, price);
    }

    function maxMint(address receiver) public view override returns (uint256) {
        uint256 maxAssets = maxDeposit(receiver);
        return maxAssets == type(uint256).max ? type(uint256).max : previewDeposit(maxAssets);
    }

    // ---------------------------------------------------------------- fees (entry fee, OZ ERC4626Fees pattern)

    function previewDeposit(uint256 assets) public view override returns (uint256) {
        return super.previewDeposit(assets - _feeOnTotal(assets));
    }

    function previewMint(uint256 shares) public view override returns (uint256) {
        uint256 assets = super.previewMint(shares);
        return assets + _feeOnRaw(assets);
    }

    function _deposit(address caller, address receiver, uint256 assets, uint256 shares) internal override {
        uint256 fee = _feeOnTotal(assets);
        super._deposit(caller, receiver, assets, shares);
        if (fee > 0 && feeRecipient != address(this)) IERC20(asset()).safeTransfer(feeRecipient, fee);
    }

    function _feeOnRaw(uint256 assets) private view returns (uint256) {
        return assets.mulDiv(entryFeeBps, BPS, Math.Rounding.Ceil);
    }

    function _feeOnTotal(uint256 assets) private view returns (uint256) {
        return assets.mulDiv(entryFeeBps, entryFeeBps + BPS, Math.Rounding.Ceil);
    }

    /// @dev Virtual-share offset hardens the vault against first-depositor inflation attacks.
    function _decimalsOffset() internal pure override returns (uint8) {
        return 6;
    }

    // ---------------------------------------------------------------- admin

    function setDepositCapUsd(uint256 capUsd) external onlyRole(RISK_MANAGER_ROLE) {
        depositCapUsd = capUsd;
        emit DepositCapUpdated(capUsd);
    }

    function setEntryFee(uint256 feeBps, address recipient) external onlyRole(RISK_MANAGER_ROLE) {
        if (feeBps > MAX_FEE_BPS) revert FeeTooHigh(feeBps);
        if (recipient == address(0)) revert ZeroAddress();
        entryFeeBps = feeBps;
        feeRecipient = recipient;
        emit EntryFeeUpdated(feeBps, recipient);
    }

    function setMaxPriceAge(uint256 maxAge) external onlyRole(RISK_MANAGER_ROLE) {
        maxPriceAge = maxAge;
        emit MaxPriceAgeUpdated(maxAge);
    }
}
